local Cached = {
  Seeds = {"Carrot","Strawberry","Blueberry","Tomato","Cauliflower","Watermelon","Green Apple","Avocado","Banana","Pineapple","Kiwi","Bell Pepper","Prickly Pear","Loquat","Feijoa"},
  Gears = { "Watering Can", "Trowel", "Recall Wrench", "Basic Sprinkler", "Advanced Sprinkler", "Godly Sprinkler", "Tanning Mirror", "Cleaning Spray", "Master Sprinkler", "Favorite Tool", "Harvest Tool", "Friendship Pot" },
  Pets = { "Kiwi", "Blood Kiwi", "Owl", "Panda", "Spotted Deer", "Golden Lab", "Frog", "Pack Bee", "Cooked Owl", "Red Dragon", "Cow", "Bunny", "Praying Mantis", "Queen Bee", "Caterpillar", "Golden Bee", "Turtle", "Dog", "Butterfly", "Disco Bee", "Firefly", "Moth", "Deer", "Red Giant Ant", "Tarantula Hawk", "Wasp", "Night Owl", "Bear Bee", "Monkey", "Honey Bee", "Squirrel", "Petal Bee", "Bee", "Moon Cat", "Cat", "Blood Owl", "Black Bunny", "Brown Mouse", "Blood Hedgehog", "Silver Monkey", "Chicken", "Chicken Zombie", "Red Fox", "Orange Tabby", "Echo Frog", "Grey Mouse", "Dragonfly", "Mole", "Raccoon", "Hedgehog", "Sea Otter", "Rooster", "Giant Ant", "Polar Bear", "Pig", "Snail" },
  Honeys = { "Flower Seed Pack", "Lavender", "Nectarshade", "Nectarine", "Hive Fruit", "Pollen Radar", "Nectar Staff", "Honey Sprinkler", "Bee Egg", "Bee Crate", "Honey Comb", "Bee Chair", "Honey Torch", "Honey Walkway" },
  Attributes = {"Pollinated", "Wet", "Frozen", "Rainbow", "Celesial", "Moonlit", "Shocked"},
  Weather = {"NightEvent","DiscoEvent","TornadoEvent","HeatwaveEvent","RainEvent","JanzenStorm","CurrentWeatherEvent","ChocolateRain","Windy","Thunderstorm","SummerHarvest","MeteorShower","KillerBunny"},
  NPCs = {["Sell NPC"] = CFrame.new(92, 4, 2)},
  EggsLocations = {
    {
      CFrame.new(-289.039246, 2.79752779, 11.7703476, 1, 0, 0, 0, 1, 0, 0, 0, 1)
    },
    {
      CFrame.new(-289.04126, 2.87552762, 3.73038578, 1, 0, 0, 0, 1, 0, 0, 0, 1)
    },
    {
      CFrame.new(-289.031219, 2.79752779, 7.74039459, 1, 0, 0, 0, 1, 0, 0, 0, 1)
    }
  },
  EggsPrice = {
    ["Common Egg"] = 50000,
    ["Uncommon Egg "] = 150000,
    ["Rare Egg"] = 600000,
    ["Legendary Egg"] = 3000000,
    ["Mythical Egg"] = 8000000,
    ["Bug Egg"] = 50000000,
    ["Common Summer Egg"] = 1000000,
    ["Rare Summer Egg"] = 25000000,
    ["Paradise Egg"] = 50000000,
  },
}
return Cached
